### ISSUE TITLE
Quota warning

### ISSUE THREAD

**Issue by PVince81** [nextcloud/user_migration#111]
- [x] Whenever there is not enough space for the export (which we can estimate somehow), display a warning before exporting.
- [x] also add note that if you're close to having no space left, versions and trashbin might expire during the export ? https://github.com/nextcloud/user_migration/pull/183 https://github.com/nextcloud/server/pull/33068

**Comment by Pytal** [comment]
### Requires

- [ ] Extend migrators with method to get estimated size of user data to be exported
- [ ] API endpoint to check whether a user can export based on various checks
- [ ] UI integration to show warnings

**Comment by come-nc** [comment]
- [ ] https://github.com/nextcloud/server/pull/32206

**Comment by Pytal** [comment]
### Plan

- [ ] New `ISizeEstimationMigrator` will be added and implemented as per https://github.com/nextcloud/server/pull/32206#issuecomment-1129072407
  - https://github.com/nextcloud/server/pull/32206
- [ ] Check estimated vs. actual archive size in various scenarios
- [ ] Improve estimate calculation as needed
- [ ] Expose estimate through an API endpoint as per https://github.com/nextcloud/user_migration/pull/135#issuecomment-1114554103
  - https://github.com/nextcloud/user_migration/pull/135
  - [ ] Round the estimate before sending a response back to the client
- [ ] Display estimate on the UI
  - https://github.com/nextcloud/user_migration/pull/136

**Comment by PVince81** [comment]
the plan looks fine :smile:

**Comment by Pytal** [comment]
Remaining tasks are the small expiration notice PRs

Quota warning itself is complete

Unhandled exceeding of user quota tracked in https://github.com/nextcloud/user_migration/issues/184
