### ISSUE TITLE
Cancel button to unqueue the export

### ISSUE THREAD

**Issue by PVince81** [nextcloud/user_migration#112]
In case there's a long queue of exports or background jobs, it might take a while until the current export/import is processed.

In that time window, we should still let the user cancel the job as it hasn't started yet.

Cancelling a running job is currently not technically possible so out of scope.

**Comment by Pytal** [comment]
### Requires
- [ ] https://github.com/nextcloud/user_migration/pull/123
- [ ] UI integration
