### ISSUE TITLE
Error: Undefined variable $importJob at /var/www/nextcloud/apps/user_migration/lib/Service/UserMigrationService.php#405

### ISSUE THREAD

**Issue by accolon** [nextcloud/user_migration#150]
I'm getting a "Level: Error" entry as stated in the title logged each time a user opens "Data migration" in the settings.

I think the null coalescing operator in line 405 causes this because it always tries to return `$importJob` if `$exportJob` is not set. However, neither variable is defined at this point when there are no jobs queued. (I'm using PHP 8.0, not sure if this behaviour is changed on other versions.)

https://github.com/nextcloud/user_migration/blob/58cfd396fe8a10d7fef55db243f235b536fae65b/lib/Service/UserMigrationService.php#L405

**Comment by bcutter** [comment]
Same for me. Export fail. PHP 8.1.

```
Error: Undefined variable $importJob at /var/www/nextcloud/apps/user_migration/lib/Service/UserMigrationService.php#405
```

**Comment by come-nc** [comment]
@bcutter No, the app is not in beta state, you can see 1.0.3 is newer than 1.0.1-beta.2. Please install 1.0.3, not the older beta.

@accolon Thank you for the report, I will fix it.

**Comment by come-nc** [comment]
@accolon Can you check if the change in #155 fix your problem, and tell me if you see any other obvious error?

I will then release a 1.0.4 with the fix.

**Comment by accolon** [comment]
Thanks, this fixed the problem. I don't see any other issues right now.
