### ISSUE TITLE
Export succcessful message on a failed export

### ISSUE THREAD

**Issue by pmarini-nc** [nextcloud/user_migration#166]
When doing an export, if the export fails for any reason, it shouldn't give the popup message below:

![image](https://user-images.githubusercontent.com/85954408/170023042-bb434254-0f0d-4f5f-b688-82b77d287a0c.png)

System Report:
[2022-05-24.md](https://github.com/nextcloud/user_migration/files/8762167/2022-05-24.md)

**Comment by Pytal** [comment]
Tracking in https://github.com/nextcloud/user_migration/issues/125
