### ISSUE TITLE
Export creates empty archive

### ISSUE THREAD

**Issue by wahve3** [nextcloud/user_migration#179]
When I try the plugin on my Nextcloud 24.0.1 snap, it creates an empty archive as a file after running for about 10 minutes and a success message. I tried this again on another non-snap Nextcloud 24 installation and there it created the archive successfully.

Has this plugin been tested on snap installations?

**Comment by come-nc** [comment]
> Has this plugin been tested on snap installations?

No, I did not even know there was snap installations.

Are there any errors in the logs? 
Sounds like a permission problem but if Nextcloud was not able to write in the user data folder you would have other trouble for sure.

Can you try an export through the occ command?
Also can you try to download the export file and double check that it is actually empty? (it could be bad size estimation by file UI)

**Comment by wahve3** [comment]
Yes, the size estimation is indeed a problem as I have seen now.

However, when I try to export an account with many files (more than 10 GB), I sometimes get errors when creating the archive. But I will check if the export is at least being created normally when I get a success message despite of the issue with the file size estimation.

**Comment by come-nc** [comment]
@wahve3 Where you able to figure out what is wrong?
Can I close this?

**Comment by wahve3** [comment]
No, I haven't been able to figure it out, but I applied a different solution to migrate users.
