### ISSUE TITLE
Does the plugin save file sharing information?

### ISSUE THREAD

**Issue by wahve3** [nextcloud/user_migration#181]
When I want to use the plugin to migrate multiple user accounts from one installation to another, does it save the information which file has been shared with whom?

**Comment by come-nc** [comment]
No, shares are currently lost by migration.
See https://github.com/nextcloud/user_migration/issues/144 which is the long term plan, transform shares into federated shares.

But in your case with multiple users migrating I am unsure how we could preserve the shares between them.

**Comment by wahve3** [comment]
Ideally, the share information is being stored in one place and I can find another way of restoring these. But I don't know that.
If it worked, though, it would provide a nice GUI option to migrate Nextcloud to another server using this plugin.

**Comment by come-nc** [comment]
Duplicate of https://github.com/nextcloud/user_migration/issues/144
