### ISSUE TITLE
Improve files migration

### ISSUE THREAD

**Issue by come-nc** [nextcloud/user_migration#19]
The export/import of files is currently done in `UserMigrationService`

It should be refactored to be in its own `IMigrationOperation` instance.

Then it should be improved to export and restore files metadata: 
- [x] Versions (Should this be done in an other migration operation from files_version app?)
- [x] file tags (contains favorites)
- [x] systemtags
- [x] and maybe comments (https://github.com/nextcloud/server/issues/30397#issuecomment-1004751678)
- [ ] mtime, etag, …?

**Comment by Pytal** [comment]
Reopening pending more files metadata

**Comment by PVince81** [comment]
I came here because I also noticed that mtime was not preserved

**Comment by PVince81** [comment]
closing in favor of more precise ticket: https://github.com/nextcloud/user_migration/issues/83
