### ISSUE TITLE
Do not export to user's root - causes sync issues

### ISSUE THREAD

**Issue by svenb1234** [nextcloud/user_migration#198]
Exporting to the user's root folder creates problems for the desktop sync clients, at least the windows one. Since it is not possible to manage which files from the user's root are synced, not even whether the user's root shoudl be synced or just some sub-folders, placing a huge file in the root folder, makes the desktop client want to sync it.

Given that exports can easily become huge compared to a notebook disk, e.g. 512 GB SSD+1 TB HDD, the desktop client always "fails" to sync and shows a warning that syncing would lower the available disk space too much. Hence the user always sees a "sync failed" status in the systray, a red icon.

This is at least annoying, maybe even dangerous because it is kind of a false alarm and thus will lead to users not catching real issues since they think that the failed status icon is only because of the export file.

Solution would be to export to a (hard-coded) sub-folder which can be (de-)selected in the sync client.

Arguably, the sync client should also offer the possibility to de-select files from the root folder.

**Comment by Pytal** [comment]
This is a https://github.com/nextcloud/desktop issue as the solution is not exclusive to user_migration and is tracked in https://github.com/nextcloud/desktop/issues/4421 and https://github.com/nextcloud/desktop/issues/3975

Feel free to add more context to the issues linked above
