### ISSUE TITLE
Design and implement a compatibility check policy

### ISSUE THREAD

**Issue by come-nc** [nextcloud/user_migration#20]
Current export contains versions from all apps and nextcloud core, but import does not check it at all.

We need to decide how the import should know if it is able to import a given file or not.

Basic strategy would be refuse to import if any app version is newer than what is installed. This is a bit drastic as it means it would be hard to migrate users across two instances in both ways as all applications would need to be the exact same version.

Clean strategy would be to ask each IMigrationOperation to give a version number for the data it outputs, which is increased when compatibility is broken. That would mean a `IMigrationOperation::getVersion()` that get stored in the versions.json instead or on top of the app versions I suppose. And a general one with the same logic for core import.

Related question is what to do when some application that was exported is not installed, and the other way around:
- If an exported application is not installed, it should be safe to ignore it, but we should still warn the user that some data was not imported
- If an installed application is missing from the import, I suppose all should be fine? (The application will be aware that there is a new user through normal mechanisms and should be able to initialize it as any other)

**Comment by Pytal** [comment]
> What about adding the following to `OCP\UserMigration\IMigrator` interface:

👌 good API for our requirements, in terms of treating older versions differently the mechanism should avoid supporting all previous versions which could become a pain

**Comment by come-nc** [comment]
> > What about adding the following to `OCP\UserMigration\IMigrator` interface:
> 
> ok_hand good API for our requirements, in terms of treating older versions differently the mechanism should avoid supporting all previous versions which could become a pain

This is why there is the canImport method, so that support for too old versions can be dropped.
But knowing the version you are importing from will still help not dropping support right away.

Like if you decide to change date format from d.m.Y to Y-m-d you can look at the version you import from to know which format to expect.

It may make more sense to add a function in IImportSource to get version information, as in a lot of cases the import operation will not need it so passing it as a parameter will look weird. I will try to open a PR for this next week and see how it feels.
I might have to provide a trait (or astract class?) that implements the classic check where you only import from older version.
