### ISSUE TITLE
Allow importing a user under an other name

### ISSUE THREAD

**Issue by come-nc** [nextcloud/user_migration#21]
Current import will import the user under its UID from the export, and will fail if there is already a user with this name.
It should be improved so that it is possible to use an other uid instead.

- It means migration could be used for renaming a user
- It will allow importing the user on an instance that already have a user with the same name.

We will need to make sure that there are no references to the old uid in the imported data, or if there are update them accordingly.

**Comment by PVince81** [comment]
this already works, I tested it locally with `occ user:import --user bob files/of/alice....zip
