### ISSUE TITLE
Suggestion - export data per users

### ISSUE THREAD

**Issue by stratege1401** [nextcloud/user_migration#242]
Hi,

so far so good.
Testing on a 24.0.5 version.

Could it be possible to have a "per users export" choice...

**Comment by Pytal** [comment]
Exported archives already contain the data of only a single user, could you elaborate?

**Comment by stratege1401** [comment]
Hi

My prod server have a  +/- 1424 users base with a 1.2 peta capacity.

I have tested your app only on my lab system ..with only one user/admin and
very few data.

So I have no real clue on the scale/speed on a real prod server.

In my mind, I thought also to used it to do a user/retention on a user
basis  when the "quit" the server.

Thanks anyway, seems to be a great tool.

**Comment by stratege1401** [comment]
Sorry, English is not my main language.

When exporting as an admin, I would like to export others users data. Not
the whole servers...

I was hoping not to scp/ssh to the server and export my /mnt/...
.../data/user104 for example

Le sam. 17 sept. 2022, 13:27, stratege1401 ***@***.***> a
écrit :

> Hi
>
> My prod server have a +/- 1424 users base with a 1.2 peta capacity.
>
> I have tested your app only on my lab system ..with only one user/admin and
> very few data.
>
> So I have no real clue on the scale/speed on a real prod server.
>
> In my mind, I thought also to used it to do a user/retention on a user
> basis when the "quit" the server.
>
> Thanks anyway, seems to be a great tool.
>
>
>
>
>

**Comment by come-nc** [comment]
It is still not clear. You can already export a single user.
If you want to export another user as an admin, then you need to use the command line, see `occ user:export` command

French:
Je ne comprends pas ta demande. Tu peux déjà exporter un seul utilisateur, c’est ce que fait l’application.
Si tu veux exporter un autre utilisateur en tant qu’admin, tu dois utiliser la ligne de commande. Regarde la commande `occ user:export`.

**Comment by stratege1401** [comment]
Merci.

I continue in English for the others...

I have several NC servers. One of them is used by a very small architect
shop. They only use the GUI for the administration... Having them using
ssh/occ is kind of "un gros bordel"... This is why I was so focus on the
GUI usage.

The occ command fits me need now.

Thank you.

Le lun. 19 sept. 2022, 11:13, Côme Chilliet ***@***.***> a
écrit :
