### ISSUE TITLE
Add support for localization

### ISSUE THREAD

**Issue by p-bo** [nextcloud/user_migration#248]
Would it be possible to ease non-English speakers using of this app by adding support for localization, ideally by following these official Nextcloud instructions for developers:
https://docs.nextcloud.com/server/latest/developer_manual/basics/front-end/l10n.html#adding-translations
please? Thanks

**Comment by come-nc** [comment]
@p-bo Localization is now set up, once translated on transifex the translations should appear in the repository as well

**Comment by p-bo** [comment]
Thanks @come-nc and @nickvergessen, translations are in works / done already :-)
