### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by Perino01** [nextcloud/user_migration#269]
After installing the App no main menue nor a submenu in Users is visible. Therefore it is not clear where to start. The app has been installed sucessfully but no additional menue or action item is provided. 
Fresh nextcloud 24.06 installation under Ubuntu 22.04 via snap.

**Comment by come-nc** [comment]
Hello, import/export is done is Data Migration in user settings.
If you want to import/export other users as an admin, you have to use the occ command.

Not sure where to document that, should it go in the readme?

**Comment by Perino01** [comment]
With your help I found the Menue button! Maybe it was a mistake by the example link cat.example.com/nextcloud because with this link I was not successful. 
This is my link:
https://cat.example.com/index.php/settings/user/user_migration

But for me the it is clearer with your hint, User Settings => Data Migration. The next unclear thing is where to find the exported data? This could be also described better for a quicker understanding.

Two other questions, for data migration as Administrator it would be great to do it as Admin for All Users in one step. Is there a chance to do this? Second question, the product would really help especially in migrating user data from old sytems (< Nextloud V24) to a fresh new installation V24. Would it be possible to provide the Data Migration App, especially for exporting User Data, also to previous versions?

**Comment by come-nc** [comment]
Can you look at https://github.com/nextcloud/user_migration/pull/270 and tell me if that seems better to you?

**Comment by Perino01** [comment]
Thx for clarifying. Also for link to the manual. The problem with this procedure is that you migrate the whole system. ,If you would like to go to a fresh and new system you won't import all data incl. applications which are partly not working properly. User Data and User Data are most important!

Regarding the docu:
Line 15: Download the resulting file called `user.nextcloud_export`, which should be located in your user folder! If your mailsystem works, then you should also get a notification via mail.

**Comment by come-nc** [comment]
> Regarding the docu: Line 15: Download the resulting file called `user.nextcloud_export`, which should be located in your user folder! If your mailsystem works, then you should also get a notification via mail.

Hum the application only fires a notification, whether it is sent by email depends on both server and user configuration I think, I cannot write that in the README as if always happening.

**Comment by mgies** [comment]
> If you want to import/export other users as an admin, you have to use the occ command.

This is exactly what im wanting to do, but I can't find documentation for that. Can you give me a hint on how to export/import a whole user incl. files, calendars, contacts, further appdata?

**Comment by Pytal** [comment]
You may use the `occ user:export` and `occ user:import` [occ](https://docs.nextcloud.com/server/latest/admin_manual/configuration_server/occ_command.html) commands @mgies and may pass the `--help` flag for command usage details

**Comment by mgies** [comment]
Awesome! Thanks a lot!

Seems this was not updated in docs for "stable" and "latest" yet:
https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/occ_command.html#user-commands

**Comment by rosa2** [comment]
Hello and thanks for your work.
Maybe to mention in documentation that admins that not have occ access the can use https://apps.nextcloud.com/apps/impersonate (and that they have to login 1 time).
Thanks @come-nc  for documenting with good English :)
