### ISSUE TITLE
Error "OCP\Files\NotFoundException: /xyz/files/user.nextcloud_export"

### ISSUE THREAD

**Issue by githubber4ever** [nextcloud/user_migration#287]
After the import was done successfully and the user.nextcloud_export gets deleted, the User Migration app throws errors in the log, even the notification was already dismissed.

**Steps to reproduce:**
1. copy user.nextcloud_export to new nextcloud instance files of user
2. data migration -> import -> select 'user.nextcloud_export' -> do import and wait until finished and dismiss (success) notification
3. delete 'user.nextcloud_export' from files
4. see multiple "OCP\Files\NotFoundException: /xyz/files/user.nextcloud_export" errors in logs

Version: Nextcloud 24.0.6 + User Migration 1.1.0

**Table 'oc_notifications':**
2	user_migration	xyz	1665851795	import	1	importDone	{"author":"xyz","targetUser":"xyz","path":"\/user.nextcloud_export"}		[]			[]

**Log entry:**
_[no app in context] Fehler: OCP\Files\NotFoundException: /xyz/files/user.nextcloud_export at <<closure>>
 0. /var/www/html/lib/private/Files/Node/LazyUserFolder.php line 59
    OC\Files\Node\Root->get("/xyz/files/user.nextcloud_export")
 1. /var/www/html/custom_apps/user_migration/lib/Notification/Notifier.php line 241
    OC\Files\Node\LazyUserFolder->get("/user.nextcloud_export")
 2. /var/www/html/custom_apps/user_migration/lib/Notification/Notifier.php line 191
    OCA\UserMigration\Notification\Notifier->getImportFile(OC\User\User {}, "/user.nextcloud_export")
 3. /var/www/html/custom_apps/user_migration/lib/Notification/Notifier.php line 81
    OCA\UserMigration\Notification\Notifier->handleImportDone(OC\Notification\Notification {}, "de")
 4. /var/www/html/lib/private/Notification/Manager.php line 376
    OCA\UserMigration\Notification\Notifier->prepare(OC\Notification\Notification {}, "de")
 5. /var/www/html/apps/notifications/lib/Controller/EndpointController.php line 111
    OC\Notification\Manager->prepare(OC\Notification\Notification {}, "de")
 6. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Notifications\Controller\EndpointController->listNotifications("v2")
 7. /var/www/html/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController(OCA\Notification ... {}, "listNotifications")
 8. /var/www/html/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch(OCA\Notification ... {}, "listNotifications")
 9. /var/www/html/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main("OCA\\Notificati ... r", "listNotifications", OC\AppFramework\ ... {}, ["v2","ocs.notif ... "])
10. /var/www/html/ocs/v1.php line 62
    OC\Route\Router->match("/ocsapp/apps/no ... s")
11. /var/www/html/ocs/v2.php line 23
    require_once("/var/www/html/ocs/v1.php")_

**Comment by come-nc** [comment]
@Pytal Do you know if it is expected for the notification to be in the database after being dismissed?

I suppose we should catch the NotFoundException anyway when building the rich object for notification as it may have been deleted even before the notification is dismissed.

**Comment by ristein** [comment]
I got a similar error, although never have used migration, error comes unregularly about twice per minute:
Anything I can do about it?

```
[no app in context] Error: OCP\Files\NotFoundException: /Username/files/user.nextcloud_export at <<closure>>

 0. /var/www/nextcloud/lib/private/Files/Node/LazyUserFolder.php line 59
    OC\Files\Node\Root->get()
 1. /var/www/nextcloud/apps/user_migration/lib/Notification/Notifier.php line 232
    OC\Files\Node\LazyUserFolder->get()
 2. /var/www/nextcloud/apps/user_migration/lib/Notification/Notifier.php line 121
    OCA\UserMigration\Notification\Notifier->getExportFile()
 3. /var/www/nextcloud/apps/user_migration/lib/Notification/Notifier.php line 74
    OCA\UserMigration\Notification\Notifier->handleExportDone()
 4. /var/www/nextcloud/lib/private/Notification/Manager.php line 368
    OCA\UserMigration\Notification\Notifier->prepare()
 5. /var/www/nextcloud/apps/notifications/lib/Controller/EndpointController.php line 111
    OC\Notification\Manager->prepare()
 6. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 225
    OCA\Notifications\Controller\EndpointController->listNotifications()
 7. /var/www/nextcloud/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
 8. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
 9. /var/www/nextcloud/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
10. /var/www/nextcloud/ocs/v1.php line 63
    OC\Route\Router->match()
11. /var/www/nextcloud/ocs/v2.php line 23
    require_once("/var/www/nextcloud/ocs/v1.php")

GET /nextcloud/ocs/v2.php/apps/notifications/api/v2/notifications
from 79.xx.xxx.xx by Username at 2022-11-04T11:30:25+00:00
```

**Comment by come-nc** [comment]
> I got a similar error, although never have used migration, error comes unregularly about twice per minute: Anything I can do about it?

Are you alone on your instance? Maybe someone else used the export?

Otherwise this means somehow a notification is triggered on exportDone for no reason. But the only place I see this notification fired is in the UserExportJob so I do not see how this could be possible :thinking:

**Comment by SophyInBetween** [comment]
I get the same problem, is there a solution jet?

**Comment by irdiOL** [comment]
Got the same problem today and i did not even start a user export. I disabled the user migration app but i would like to know why this happen and how can it be solved for instances that need the user migration tool. Thank you!!

**Comment by arnowelzel** [comment]
Same here - Nextcloud 28.0.1, User migration 5.0.0

**Comment by degrees57** [comment]
I was also getting this error, once every 60 seconds.  User Migration version 4.0.1, on Nextcloud 27.1.5

I did use the User Migration app a while ago, but I don't have a need for it anymore.

Disabling the User Migration app appears to have stopped the spamming of the log file with this error message.

**Comment by githubber4ever** [comment]
@Pytal will #608 fix this issue?

**Comment by Pytal** [comment]
Yes @githubber4ever, will close this issue then
