### ISSUE TITLE
Using/Porting user_migration to old Nextcloud release

### ISSUE THREAD

**Issue by jensb** [nextcloud/user_migration#307]
I need to migrate a number of users away from a very old NC release (15.0.5) which is being replaced by a hosted one (to which I have no command line access).
The user_migration app doesn't work on Nextcloud 15, but I can create a commandline script which produces a compatible migration archive if I know the archive format (and - if you like - add it to this app as a supplement).
This would also help creating migration archives for Nextcloud from completely different cloud or storage systems.

So: Is the archive format documented anywhere?

**Comment by come-nc** [comment]
> So: Is the archive format documented anywhere?

No, the only technical documentation is about how to implement a migrator: https://docs.nextcloud.com/server/latest/developer_manual/digging_deeper/user_migration.html

You will have to look through the code of https://github.com/nextcloud/user_migration/blob/main/lib/Service/UserMigrationService.php#L185
And the code of each migrator for each application:

- https://github.com/nextcloud/user_migration/blob/main/lib/Migrator/FilesMigrator.php
- https://github.com/nextcloud/server/blob/master/apps/dav/lib/UserMigration/CalendarMigrator.php
- https://github.com/nextcloud/server/blob/master/apps/dav/lib/UserMigration/ContactsMigrator.php
- https://github.com/nextcloud/server/blob/master/apps/settings/lib/UserMigration/AccountMigrator.php
- https://github.com/nextcloud/server/blob/master/apps/files_trashbin/lib/UserMigration/TrashbinMigrator.php
- Any other migrator implemented by an application that you use. I only know of forms that have one, but there may be others out there.
