### ISSUE TITLE
Export data from other apps

### ISSUE THREAD

**Issue by Olen** [nextcloud/user_migration#309]
It would be great if the user data from other apps, like deck, ownnotes etc. could be part of the export (and import).

**Comment by Pytal** [comment]
App developers can integrate with the `user_migration` API as described in our documentation https://docs.nextcloud.com/server/stable/developer_manual/digging_deeper/user_migration.html to provide export/import functionality

One example is in the forms app https://github.com/nextcloud/forms/pull/1243, and integration for the deck app is tracked in https://github.com/nextcloud/deck/issues/3828

**Comment by Olen** [comment]
Thanks.  Did not find that.
