### ISSUE TITLE
Import fails when user had comments on shared files

### ISSUE THREAD

**Issue by mgies** [nextcloud/user_migration#334]
I am in the process of migrating some users from one to another nextcloud instance vie occ command.

On export, all shares are lost, this I know. But has a user made comments on files, which were not his own, but part of a shared folder owned by someone else, thes comments get exportet.

When importing on the new instance, the file cannot be found and thus the comment cannot be imported. The whole import aborts and fails.

Comments on files not owned by the user shouldn't be exported. At least as long as shares are not exported as well.

**Comment by mgies** [comment]
One further info: all users were deactivated before exporting. Don't know if that changes anything...

**Comment by styt** [comment]
Hi, I have the similar issue. Trying to run export and gui says successful but no file is created. 
Also running NC 25 but in a docker container.
