### ISSUE TITLE
Loading Data Migration Fails (unexpected 'protected')

### ISSUE THREAD

**Issue by pajades** [nextcloud/user_migration#370]
Opening Data Migration from the admin menu, all I see is this:
![image](https://user-images.githubusercontent.com/60847505/222312927-ce23b06c-776b-4edf-818c-2a7dee6afe98.png)
Clicking EXPORT just pops up another "Unkown Error" notification

System log shows the following error:
`Exception: syntax error, unexpected 'protected' (T_PROTECTED), expecting variable (T_VARIABLE) in file '/var/www/nextcloud/apps/passwords/lib/UserMigration/PasswordsMigrator.php' line 58`

Seems to have something to do with the 'Passwords' app?

**Comment by Pytal** [comment]
Please see https://github.com/marius-wieschollek/passwords/issues/556

You may open an issue in https://github.com/marius-wieschollek/passwords

**Comment by pajades** [comment]
Thank you - 'Passwords' was, in fact, the cause. 
Once the app was disabled, the export functioned **_perfectly_**!
