### ISSUE TITLE
Release 4.0 broke support for PHP 7.4 on NC25

### ISSUE THREAD

**Issue by tcitworld** [nextcloud/user_migration#420]
Nextcloud 25 oldest supported PHP version is PHP 7.4.

https://github.com/nextcloud/user_migration/pull/402 and https://github.com/nextcloud/user_migration/pull/408 make use of PHP8.0+ exclusive syntax.

Moreover, because of the signature change introduced in https://github.com/nextcloud/server/pull/38104, it's not possible to have a release which is compatible with both 25 (with 7.4 compatibility) and 27.

Therefore I suggest to make another 4.0.1 release with PHP8.0+ syntax removed to fix 25 instances, then bump to 5.0.0 for a 26+ exclusive release. You can find such code in branch ` fix-nc25-php7.4-compat` (but it's not compatible with 27 !)

Otherwise we can have a 4.0.1 release based on `stable25`'s code, but it will miss changes from 4.0.0. :s

Ref: https://help.nextcloud.com/t/error-after-updating-to-version-25-0-6-1/162279

@Pytal @come-nc

**Comment by Pytal** [comment]
Thanks for the heads up @tcitworld!

Closed by https://github.com/nextcloud/user_migration/pull/424

**Comment by Pytal** [comment]
NC25 + 26 compatible version is v3.0.0
