### ISSUE TITLE
Support migrating of Tasks / Deck data

### ISSUE THREAD

**Issue by privatemaker** [nextcloud/user_migration#523]
In migrating some users from an **Old Instance** to a **New Instance**, where database migration is not an option, I discovered the `User Migration` app only supports data from a few apps. 

Since `User Migration` already supports migrating Calendar data I am curious why it does not support migrating the calendars generated via Deck (which are accessible via the Tasks & Calendar) app.

Is this just that no one has implemented the correct [PHP Classes](https://docs.nextcloud.com/server/stable/developer_manual/digging_deeper/user_migration.html) in `Deck` and/or `Tasks`? Or is there some uniqueness of *those* calendars generated by other apps which makes this difficult?

Also, should this be opened in either of those app repos instead of here?

**Comment by Pytal** [comment]
Because Deck and Tasks calendars are automatically generated from their respective data a dedicated migrator for each app, i.e. https://github.com/nextcloud/deck/issues/3828, should be added to ensure data consistency

Please open an issue in the tasks repo as well if you'd like @privatemaker :)
