### ISSUE TITLE
Allow selective data export/import

### ISSUE THREAD

**Issue by Pytal** [nextcloud/user_migration#55]
Users should be able to choose which apps/data to export/import

**Comment by PVince81** [comment]
seems we have something for export at least ?

**Comment by Pytal** [comment]
Yes

- [x] Allow selective data export https://github.com/nextcloud/user_migration/pull/81
- [ ] Allow selective data import

**Comment by PVince81** [comment]
import out of scope for 0.1, users must pick the right stuff when exporting

**Comment by PVince81** [comment]
for occ, see https://github.com/nextcloud/user_migration/issues/94
