### ISSUE TITLE
Export finished but file is not to be seen.

### ISSUE THREAD

**Issue by heviiguy** [nextcloud/user_migration#561]
If we can trust the Dialogue upon completion of the tasks, I've successfully exported the migration files of 2 Users. Although the readme doesn't state where these files would be dumped to, I assume that they might be found in the User's "Files" directory. Alas, na-da, nothing, crickets; no such export files are to be found. Any suggestions?

**Comment by Lazymin3r** [comment]
I was having a similar problem and found the file (user.nextcloud_export) under the "All Files" directory of the File's app, I actually found it by clicking on the notifications.

**Comment by Pytal** [comment]
Can you see the export file when clicking the notifiation @heviiguy?

**Comment by heviiguy** [comment]
> Can you see the export file when clicking the notifiation @heviiguy?

I'm so sorry, @Pytal, I've been out for the last couple of weeks. It's quite arrogant of me for not having checked my messages. Thank-you so much for having had responded. In any case, I've resolved the issue by simply doing a manual upgrade after having copied the entire original directory for backup.
