### ISSUE TITLE
Migration failed caused by trashbin errors...

### ISSUE THREAD

**Issue by MarcS1975** [nextcloud/user_migration#575]
I exported all user data from NC 27.0.1. and imported into a newly installed NC 27.1.5 but no changes are visible in new profile.

1) export estimated the export file as 124MB but actually created a file with 4.3MB
2) Export created the following log file error 

_`[user_migration] Error: OCP\UserMigration\UserMigrationException: Could not export trashbin: Failed to copy file into files_trashbin/files/files/1_1_b05ee8024e334921b93d9ee04665ac94.json.d1695900612 in archive at <<closure>>_

My Full Export error message here:  
**https://pastebin.com/i8PhKAXG**

`3) Import created the following error message:
**https://pastebin.com/Ux4Wqadm**

**Comment by MarcS1975** [comment]
I found the problem. The data/files folder had the wrong permissions set. After changing 
`from drwxr--r-x  to drwxr-sr-x  
` 
the export worked.
I do not know how the permissions got set incorrectly though.

**Comment by Pytal** [comment]
Thanks for the update @MarcS1975!

If you run into any more issues with files permissions please report them at https://github.com/nextcloud/server

**Comment by MarcS1975** [comment]
I actually think its a Nextcloud docker container issue. The container should take care of the permissions when mounting folders from outside into the container.

**Comment by Pytal** [comment]
I see, then feel free to report any issues at https://github.com/nextcloud/all-in-one or https://github.com/nextcloud/docker or the respective NC docker repo

**Comment by MarcS1975** [comment]
I did report it at nextcloud / docker but they closed the ticket and asked me to raise the issue else where...It's a shame because I think it hinders to utilise Nextcloud's main purpose of "sharing files".
