### ISSUE TITLE
feature request: rename to nc-data migration

### ISSUE THREAD

**Issue by JimmyKater** [nextcloud/user_migration#642]
as there is at least one other app on the store that installs under setup as "data migration"  - i can find google integration & dropbox intregration in personal setting under "data migration" as well... though with a different icon - I was asking myself if it wasn't possible to slightly rename the app just to make it more distinguishable from that other "data migration"-entry.

Well so I wantedt to suggest to call it

`nc-data migration`

just to make it clearer what's it all about.

what do you think?

**Comment by JimmyKater** [comment]
or even better

`nc-user migration` ?

**Comment by Pytal** [comment]
We had decided on merging the two sections in https://github.com/nextcloud/user_migration/issues/401

If you have further thoughts feel free to leave a comment in https://github.com/nextcloud/user_migration/issues/401 @JimmyKater
