### ISSUE TITLE
Import reports success, no data is imported

### ISSUE THREAD

**Issue by kubuntu-newbie** [nextcloud/user_migration#663]
I exported a single user data from Nextcloud 28.0.4 (Kubernetes version 1.6.59, Train: charts) running on TrueNAS (uses PostgresSQL database) and then imported that data to the  Nextcloud 27.1.8, snap version (uses MySQL). No errors were reported, and as far as I can tell all apps are the same or newer versions on the snap installation and the User Migration app on the recipient/destination Nextcloud is 4.0.1

None of the data is migrated (files, photos, calendar, contacts)

Where do I begin to troubleshoot?

Thank you!

**Comment by Pytal** [comment]
Did you use the occ command or the web UI?

**Comment by Pytal** [comment]
Is there anything shown when running: `occ background-job:list -l 1000 | rg 'import'` ?

**Comment by kubuntu-newbie** [comment]
I used the web UI. Tried again with the export file created after updating Nextcloud to v29 on TrueNAS.

occ background-job:list -l 1000 shows | grep -i import
| 239 | OCA\UserMigration\BackgroundJob\UserImportJob                   | 1970-01-01T00:00:00+00:00 | {"id":1}            |
while import is running
and nothing after the job is done

**Comment by kubuntu-newbie** [comment]
got a couple of errors in the logs (UI still reported success)

Using ${expr} (variable variables) in strings is deprecated, use {${expr}} instead at /var/snap/nextcloud/41512/nextcloud/extra-apps/user_migration/lib/Service/UserMigrationService.php#237

and

"app":"user_migration","method":"","url":"--","message":"Invalid or uninitialized Zip object","userAgent
":"--","version":"27.1.8.1","exception":{"Exception":"ValueError","Message":"Invalid or uninitialized Zip object","Code":0,"Trace":[{"file":"/snap/nextcloud/41512/htdocs/lib/private/Archive/ZIP.php","line":171
,"function":"getFromName","class":"ZipArchive","type":"->"},{"file":"/var/snap/nextcloud/41512/nextcloud/extra-apps/user_migration/lib/ImportSource.php","line":56,"function":"getFile","class":"OC\\Archive\\ZIP
","type":"->"},{"file":"/var/snap/nextcloud/41512/nextcloud/extra-apps/user_migration/lib/ImportSource.php","line":148,"function":"getFileContents","class":"OCA\\UserMigration\\ImportSource","type":"->"},{"fil
e":"/var/snap/nextcloud/41512/nextcloud/extra-apps/user_migration/lib/Service/UserMigrationService.php","line":234,"function":"getMigratorVersions","class":"OCA\\UserMigration\\ImportSource","type":"->"},{"fil
e":"/var/snap/nextcloud/41512/nextcloud/extra-apps/user_migration/lib/BackgroundJob/UserImportJob.php","line":100,"function":"import","class":"OCA\\UserMigration\\Service\\UserMigrationService","type":"->"},{"
file":"/snap/nextcloud/41512/htdocs/lib/public/BackgroundJob/Job.php","line":81,"function":"run","class":"OCA\\UserMigration\\BackgroundJob\\UserImportJob","type":"->"},{"file":"/snap/nextcloud/41512/htdocs/li
b/public/BackgroundJob/QueuedJob.php","line":57,"function":"start","class":"OCP\\BackgroundJob\\Job","type":"->"},{"file":"/snap/nextcloud/41512/htdocs/lib/public/BackgroundJob/QueuedJob.php","line":47,"functi
on":"start","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"},{"file":"/snap/nextcloud/41512/htdocs/cron.php","line":152,"function":"execute","class":"OCP\\BackgroundJob\\QueuedJob","type":"->"}],"File":"/s
nap/nextcloud/41512/htdocs/lib/private/Archive/ZIP.php","Line":171,"message":"Invalid or uninitialized Zip object","exception":{},"CustomMessage":"Invalid or uninitialized Zip object"}}

**Comment by kubuntu-newbie** [comment]
running nextcloud.occ user:import user.nextcloud_export command returns:

Importing from user.nextcloud_export…
[ERROR] Failed to get migrators versions

**Comment by kubuntu-newbie** [comment]
never mind, it is a duplicate of https://github.com/nextcloud-snap/nextcloud-snap/issues/2335

the workaround is to unzip the export file and rezip it so it can be unzipped by libzip used in snap

**Comment by kubuntu-newbie** [comment]
interestingly enough, after re-zipping the file, web ui works but command line import command (nextcloud.occ user:import user.nextcloud_export) will still fail with the [ERROR] Failed to get migrators versions error

**Comment by Pytal** [comment]
Are there any additional messages when passing `-vvv` ?
