### ISSUE TITLE
User migration settings UI screenshots

### ISSUE THREAD

**Issue by Pytal** [nextcloud/user_migration#75]
Tracking design feedback on latest state of https://github.com/nextcloud/user_migration/pull/6 and https://github.com/nextcloud/user_migration/pull/97

**Comment by Pytal** [comment]
### Data migration settings
![image](https://user-images.githubusercontent.com/24800714/162350381-0d8eb97d-a707-46df-ac0a-9580ffbf5a9a.png)

### Export in progress modal
![image](https://user-images.githubusercontent.com/24800714/162350413-6cf9f4d0-975d-40cd-8db2-0c0a37025cb4.png)

### Import file picker
![image](https://user-images.githubusercontent.com/24800714/162350429-9b0bc5d9-8ae3-4a29-92c8-bafd7d4dc89e.png)

**Comment by PVince81** [comment]
the button is wayyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyyy too large

**Comment by jancborchardt** [comment]
Very nice work! :)

> Export in progress modal

I assume that's what @PVince81 means with the large button, the button being too wide in the background. Buttons on the other screenshots look good.

The modal could have a nice export icon on top (like emptycontent), "Export in progress" as heading, and a short text like:
"Please do not use your account while exporting."

> State change based on job status

Is this when you close the modal? Then the "Show status" button should be the secondary button so you quickly see how to bring it up again.

**Comment by Pytal** [comment]
> I assume that's what @PVince81 means with the large button, the button being too wide in the background. Buttons on the other screenshots look good.

Yep if you look at my initial comment from the list of comment edits it wil show the overly wide button in the first screenshot

> The modal could have a nice export icon on top (like emptycontent), "Export in progress" as heading, and a short text like: "Please do not use your account while exporting."

Gonna add that :)

> Is this when you close the modal? Then the "Show status" button should be the secondary button so you quickly see how to bring it up again.

Yes or when you reload the page, could you elaborate on what you mean by secondary?

**Comment by jancborchardt** [comment]
@Pytal also just mentioning here: Looks all great, with the added "Close" button that part is obvious then too. :) :+1:

**Comment by PVince81** [comment]
closing, the UI is merged
