### ISSUE TITLE
Preserve mtime, etag

### ISSUE THREAD

**Issue by PVince81** [nextcloud/user_migration#83]
Preserve more file metadata like mtime and etag.

Not preserving leads to apps like recommendations thinking that all files are new and then recommends them all.

This is also important in case the user has local data and they simply reconfigure their desktop client to point at the new account and keep the local data. I believe that having a different mtime would cause the desktop client to redownload all files while having the same mtime would keep them. (I was able to keep the local files with a new account yesterday, that's how I know!)

**Comment by come-nc** [comment]
Questions:
- How? Node (parent class of Folder/File) has getMTime and getEtag but no setter function than I can see. Do we have any code messing with mtime or etag currently?
- Is it safe and will the instance behave correctly with files that appears to be older than its installation?
- Attack vector? Do we need to protect against really old date or future date?

**Comment by PVince81** [comment]
for etag, it's a different discussion which I'm afraid will be much more complicated
keeping etags will likely not be necessary because the user will need to setup the desktop client from scratch for the new account, and for new accounts the client doesn't know any etags, so they are not relevant

**Comment by PVince81** [comment]
I don't think we should preserve etags because of the above reason.

mtime preservation has been merged, closing
